spring:
    application:
        name: employeeservice
    config:
        import: optional:configserver:http://configserver:8888
    datasource:
        url: jdbc:mysql://localhost:3306/Employee
        username: root
        password: Gamer@123
server:
    port: 8081
